### ISSUE TITLE
Can i connect without TLS

### ISSUE THREAD

**Issue by drony** [rcaelers/esp32-beacon-scanner#1]
Can i connect without TLS?

[0;31mE (13088) NET: Error: mbedtls_ssl_setup SSL - Memory allocation failed -32512[0m
[0;31mE (13088) MQTT: Error: connect TLS protocol error[0m
Heap summary for capabilities 0x00001000:
  At 0x3ffbbb28 len 8192 free 0 allocated 8028 min_free 0
    largest_free_block 0 alloc_blocks 33 free_blocks 0 total_blocks 33
  At 0x3ffb2730 len 22736 free 0 allocated 22196 min_free 0
    largest_free_block 0 alloc_blocks 127 free_blocks 0 total_blocks 127
  At 0x3ffaff10 len 240 free 0 allocated 196 min_free 0
    largest_free_block 0 alloc_blocks 3 free_blocks 0 total_blocks 3
  At 0x3ffd1fb8 len 57416 free 140 allocated 56548 min_free 0
    largest_free_block 64 alloc_blocks 168 free_blocks 6 total_blocks 174
  At 0x3ffe0440 len 15296 free 0 allocated 15188 min_free 0
    largest_free_block 0 alloc_blocks 19 free_blocks 0 total_blocks 19
  At 0x3ffe4350 len 113840 free 28212 allocated 85264 min_free 11524
    largest_free_block 26068 alloc_blocks 69 free_blocks 14 total_blocks 83

**Comment by rcaelers** [comment]
Currently, Only MQTT via TLS is supported.

**Comment by rcaelers** [comment]
Add support for MQTT without TLS.
