### ISSUE TITLE
UUID output in MQTT topic

### ISSUE THREAD

**Issue by nero01** [rcaelers/esp32-beacon-scanner#5]
Hello,
thank you for this great beacon scanner and your hard work.
Could you please add the UUID of the current device scanned into the MQTT topic?
It has to be added into the function BLEScannerDriver::on_scan_timer() and is provided in the adv_data of the BLE spec.
So the output of the MQTT message would be:

{"adv_data":"adb_data_base64","bda":"bda_base64","mac":"AA:AA:AA:AA:AA:AA","rssi":-80, "UUID": "E2C56FFF-DFFF-48DF-B060-D0F5A71096E0"}

Please tell me if you need any logs from me.

**Comment by rcaelers** [comment]
Added ibeacon info in MQTT message.

**Comment by rcaelers** [comment]
Format is slightly different:

{“adv_data”:”\<data>”, ”bda”:” "\<bda>”, ”ibeacon”: { “major”:\<major>,”minor”:\<minor>,”power”:\<power>,”uuid”:"\<uuid>"},”mac”:\<mac>,”rssi”:\<rssi>}
